/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.utfpr.wellington.visao.swing;

import br.com.utfpr.wellington.modelo.rn.UsuarioRN;
import br.com.utfpr.wellington.modelo.vo.Cargo;
import br.com.utfpr.wellington.modelo.vo.Endereco;
import br.com.utfpr.wellington.modelo.vo.Funcionario;
import br.com.utfpr.wellington.modelo.vo.Pessoa;
import br.com.utfpr.wellington.modelo.vo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author ferre
 */
public class CadUsuario extends javax.swing.JPanel {

    /**
     * Creates new form CadUsuario
     */
    public CadUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comple = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        dtAdimissao = new javax.swing.JFormattedTextField();
        telefone = new javax.swing.JFormattedTextField();
        dtNasc = new javax.swing.JFormattedTextField();
        cargo = new javax.swing.JComboBox<>();
        cep = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Funcionarios");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 768, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Informações do Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Senha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        senha.setBackground(new java.awt.Color(255, 255, 255));
        senha.setForeground(new java.awt.Color(0, 0, 0));
        add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 140, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Informações Pessoais");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nome Completo:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setForeground(new java.awt.Color(0, 0, 0));
        add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Data de Nascimento:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CPF:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 231, -1, -1));

        cpf.setBackground(new java.awt.Color(255, 255, 255));
        cpf.setForeground(new java.awt.Color(0, 0, 0));
        add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 227, 140, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telefone:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 231, -1, -1));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Masculino", "Feminino ", "Outros", " " }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 226, 118, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sexo:");
        jLabel11.setToolTipText("");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 233, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Endereco:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rua:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 324, -1, -1));

        rua.setBackground(new java.awt.Color(255, 255, 255));
        rua.setForeground(new java.awt.Color(0, 0, 0));
        add(rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 140, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Numero:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 324, -1, -1));

        numero.setBackground(new java.awt.Color(255, 255, 255));
        numero.setForeground(new java.awt.Color(0, 0, 0));
        add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 320, 140, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Bairro:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 324, -1, -1));

        bairro.setBackground(new java.awt.Color(255, 255, 255));
        bairro.setForeground(new java.awt.Color(0, 0, 0));
        add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 320, 140, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Ciadade:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 366, -1, -1));

        cidade.setBackground(new java.awt.Color(255, 255, 255));
        cidade.setForeground(new java.awt.Color(0, 0, 0));
        add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 362, 140, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Complemento:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 366, -1, -1));

        comple.setBackground(new java.awt.Color(255, 255, 255));
        comple.setForeground(new java.awt.Color(0, 0, 0));
        add(comple, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 362, 140, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Estado:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 408, -1, -1));

        estado.setBackground(new java.awt.Color(255, 255, 255));
        estado.setForeground(new java.awt.Color(0, 0, 0));
        add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 404, 140, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Pais:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 408, -1, -1));

        pais.setBackground(new java.awt.Color(255, 255, 255));
        pais.setForeground(new java.awt.Color(0, 0, 0));
        pais.setText("Brasil");
        add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 404, 140, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("CEP:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 366, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Informações sobre o Contrato");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 471, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Data Admissao:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 515, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Salario:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 515, -1, -1));

        salario.setBackground(new java.awt.Color(255, 255, 255));
        salario.setForeground(new java.awt.Color(0, 0, 0));
        add(salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 511, 140, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Cargo:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 515, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 124, 723, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(723, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, -1, -1));

        jPanel6.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 446, 723, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 714, 43));

        dtAdimissao.setBackground(new java.awt.Color(255, 255, 255));
        dtAdimissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dtAdimissao.setForeground(new java.awt.Color(0, 0, 0));
        try {
            dtAdimissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(dtAdimissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 514, 131, 20));

        telefone.setBackground(new java.awt.Color(255, 255, 255));
        telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 227, 129, 28));

        dtNasc.setBackground(new java.awt.Color(255, 255, 255));
        dtNasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dtNasc.setForeground(new java.awt.Color(0, 0, 0));
        try {
            dtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtNascActionPerformed(evt);
            }
        });
        add(dtNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 140, 30));

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Gerente", "Garçon", "Caixa", "Balconista", "Chapeiro", "Cozinheiro", "Repositor" }));
        add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 140, 30));

        cep.setBackground(new java.awt.Color(255, 255, 255));
        cep.setForeground(new java.awt.Color(0, 0, 0));
        add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        Endereco endereco = new Endereco();
        Cargo cargo = new Cargo();
        Funcionario funcionario = new Funcionario();
        Pessoa pessoa = new Pessoa();
        Usuario usuario = new Usuario();
        
        try {
            endereco.setNomeRua(rua.getText());
            endereco.setNumero(numero.getText());
            endereco.setBairro(bairro.getText());
            endereco.setComplemento(comple.getText());
            endereco.setCep(Integer.parseInt(cep.getText()));
            endereco.setCidade(cidade.getText());
            endereco.setEstado(estado.getText());
            endereco.setPais(pais.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Preencha o Endereço Corretamente");
        }
        
        try {
            switch (this.cargo.getSelectedIndex()) {
                case 1:
                    cargo.setNomeCargo("Gerente");
                    break;
                case 2:
                    cargo.setNomeCargo("Garçon");
                    break;
                case 3:
                    cargo.setNomeCargo("Caixa");
                    break;
                case 4:
                    cargo.setNomeCargo("Balconista");
                    break;
                case 5:
                    cargo.setNomeCargo("Chapeiro");
                    break;
                case 6:
                    cargo.setNomeCargo("Cozinheiro");
                    break;
                case 7:
                    cargo.setNomeCargo("Repositor");
                    break;
                default:
                    break;
            }
            funcionario.setCargo(cargo);
            funcionario.setDataAdmissao(dtAdimissao.getText());
            funcionario.setSalario(Float.parseFloat(salario.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Preencha as Informações do Contrato Corretamente");
        }
         
        try {
            pessoa.setCpf(Integer.parseInt(cpf.getText()));
            pessoa.setNome(nome.getText());
            pessoa.setDataNascimento(dtNasc.getText());
            pessoa.setTelefone(telefone.getText());     
            switch (sexo.getSelectedIndex()) {
                case 1:
                    pessoa.setSexo("Masculino");
                    break;
                case 2:
                    pessoa.setSexo("Feminino");
                    break;
                case 3:
                    pessoa.setSexo("Outros");
                    break;
                default:
                    break;
            }
            pessoa.setEndereco(endereco);
            pessoa.setFuncionario(funcionario);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Preencha as Informações Pessoais Corretamente");
        }
        
        try {
            usuario.setNome(username.getText());
            usuario.setPessoa(pessoa);
            usuario.setSenha(senha.getText());
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Preencha as Informações do Usuario Corretamente");
        }
        
        try {
            UsuarioRN usuarioRN = new UsuarioRN();
            usuarioRN.salvar(usuario);
            JOptionPane.showMessageDialog(null,"Usuario cadstrado com sucesso!!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"O usuario nã foi cadastrado com sucesso!");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void dtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtNascActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField comple;
    private javax.swing.JTextField cpf;
    private javax.swing.JFormattedTextField dtAdimissao;
    private javax.swing.JFormattedTextField dtNasc;
    private javax.swing.JTextField estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField senha;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
