/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.utfpr.wellington.visao.swing;

import br.com.utfpr.wellington.modelo.dao.generic.GenericDAO;
import br.com.utfpr.wellington.modelo.dao.generic.GenericDAOimpl;
import br.com.utfpr.wellington.modelo.rn.EstoqueRN;
import br.com.utfpr.wellington.modelo.vo.Bebidas;
import br.com.utfpr.wellington.modelo.vo.Estoque;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferre
 */
public class EstoqueCad extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public EstoqueCad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        a = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        vVenda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tipoB = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        validade = new javax.swing.JTextField();
        nomeb1 = new javax.swing.JLabel();
        cadastro = new javax.swing.JButton();
        dtCompra = new javax.swing.JTextField();
        nomeb2 = new javax.swing.JLabel();
        vLote = new javax.swing.JTextField();
        nomeb3 = new javax.swing.JLabel();
        qtd = new javax.swing.JTextField();
        nomeb4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Data Compra", "Quantidade", "Valor Lote", "Tipo", "Valiade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 760, 320));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estoque");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 760, 10));

        a.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        a.setText("Nome:");
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        nome.setBackground(new java.awt.Color(255, 255, 255));
        nome.setForeground(new java.awt.Color(0, 0, 0));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, 30));

        vVenda.setBackground(new java.awt.Color(255, 255, 255));
        vVenda.setForeground(new java.awt.Color(0, 0, 0));
        vVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVendaActionPerformed(evt);
            }
        });
        jPanel1.add(vVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 140, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Valor Venda:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 30));

        tipoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Suco", "Cerveja", "Refrigerante" }));
        jPanel1.add(tipoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tipo:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, 30));

        validade.setBackground(new java.awt.Color(255, 255, 255));
        validade.setForeground(new java.awt.Color(0, 0, 0));
        validade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validadeActionPerformed(evt);
            }
        });
        jPanel1.add(validade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        nomeb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomeb1.setForeground(new java.awt.Color(0, 0, 0));
        nomeb1.setText("Validade:");
        jPanel1.add(nomeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        cadastro.setBackground(new java.awt.Color(0, 255, 0));
        cadastro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cadastro.setForeground(new java.awt.Color(255, 255, 255));
        cadastro.setText("Cadastrar");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });
        jPanel1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 714, 43));

        dtCompra.setBackground(new java.awt.Color(255, 255, 255));
        dtCompra.setForeground(new java.awt.Color(0, 0, 0));
        dtCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtCompraActionPerformed(evt);
            }
        });
        jPanel1.add(dtCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, 30));

        nomeb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomeb2.setForeground(new java.awt.Color(0, 0, 0));
        nomeb2.setText("Data Compra:");
        jPanel1.add(nomeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 30));

        vLote.setBackground(new java.awt.Color(255, 255, 255));
        vLote.setForeground(new java.awt.Color(0, 0, 0));
        vLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLoteActionPerformed(evt);
            }
        });
        jPanel1.add(vLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, 30));

        nomeb3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomeb3.setForeground(new java.awt.Color(0, 0, 0));
        nomeb3.setText("Valor Lote:");
        jPanel1.add(nomeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 30));

        qtd.setBackground(new java.awt.Color(255, 255, 255));
        qtd.setForeground(new java.awt.Color(0, 0, 0));
        qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdActionPerformed(evt);
            }
        });
        jPanel1.add(qtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 90, 30));

        nomeb4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomeb4.setForeground(new java.awt.Color(0, 0, 0));
        nomeb4.setText("Quantidade:");
        jPanel1.add(nomeb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void vVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vVendaActionPerformed

    private void validadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validadeActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        
        Bebidas bebidas = new Bebidas();
        Estoque estoque = new Estoque();
        
        try {
            bebidas.setNome(nome.getText());
            bebidas.setPreco(Float.parseFloat(vVenda.getText()));
            switch (tipoB.getSelectedIndex()) {
                case 1:
                    bebidas.setTipo("Suco");
                    break;
                case 2:
                    bebidas.setTipo("Cerveja");
                    break;
                case 3:
                    bebidas.setTipo("Refrigerante");
                    break;
                default:
                    break;
            }
            bebidas.setValidade(validade.getText());
            
            estoque.setBebidas(bebidas);
            estoque.setDataCompra(dtCompra.getText());
            estoque.setQtdTotal(Integer.parseInt(qtd.getText()));
            estoque.setValorLote(Float.parseFloat(vLote.getText()));
            
            GenericDAO<Estoque> genericDao = new GenericDAOimpl<Estoque>(){};
            genericDao.Cadastrar(estoque);
            JOptionPane.showMessageDialog(null,"O cadastro foi realizado com sucesso!");
            
            preenchertabela();          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Preencha as Informações do Cadastro Corretamente");
        }
        
    }//GEN-LAST:event_cadastroActionPerformed

    private void dtCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtCompraActionPerformed

    private void vLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLoteActionPerformed
        // TODO add your dling code here:
    }//GEN-LAST:event_vLoteActionPerformed

    private void qtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueCad().setVisible(true);
                preenchertabela();
            }
        });
    }
    
    public static void preenchertabela(){
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        
        Object colunas[] = new Object[7];
        
        EstoqueRN estoqueRN = new EstoqueRN();
        
        List<Estoque> estoques = estoqueRN.listarEstoque();
        
        for (Estoque estoque : estoques) {
            
            colunas[0] = estoque.getId();
            colunas[1] = estoque.getBebidas().getNome();
            colunas[2] = estoque.getDataCompra();
            colunas[3] = estoque.getQtdTotal();
            colunas[4] = estoque.getValorLote();
            colunas[5] = estoque.getBebidas().getTipo();
            colunas[6] = estoque.getBebidas().getValidade();
            model.addRow(colunas);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton cadastro;
    private javax.swing.JTextField dtCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeb1;
    private javax.swing.JLabel nomeb2;
    private javax.swing.JLabel nomeb3;
    private javax.swing.JLabel nomeb4;
    private javax.swing.JTextField qtd;
    public static javax.swing.JTable tabela;
    private javax.swing.JComboBox<String> tipoB;
    private javax.swing.JTextField vLote;
    private javax.swing.JTextField vVenda;
    private javax.swing.JTextField validade;
    // End of variables declaration//GEN-END:variables
}
